algoritmo "contagem_inteligente"
var
c,n,s:inteiro
inicio
escreval("CONTAGEM INTELIGENTE")
escreval("_______________________")
escreva("Inicio: ")
leia (n)
escreva("Fim ")
leia (s)
     c<-n
     enquanto (c<=10) faca
     escreva("",c,"...")
     c<-c+1
           se (s>n) entao
           c<-s
           enquanto (c<=n) faca
           escreva("",c,"...")
           c<-c-1






           fimse
     fimenquanto
fimalgoritmo
